---
title: "10/01 dplyr & tidyr"
author: "River Sung"
date: "01/10/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**dplyr**
Summarize
```{r}
library(dplyr)
summarised <- summarise(iris, Mean.Width = mean(Sepal.Width))
head(summarised)
```

Manipulate - select 
```{r}
# by column names
# the function "select" comes from more than one pacjkage, this is specifying which package to use, also dont need to use the library() function to load package 
selection1 <- dplyr::select(iris, Sepal.Length, Sepal.Width, Petal.Length)
head(selection1) 

# by column range
# just like when giving 2:5 instruction, R prints out [2, 3, 4, 5]
# print only 4 lines
selection2 <- dplyr::select(iris, Sepal.Length:Petal.Length)
head(selection2, 4)

# by column range number
# c() combine function
selection3 <- dplyr::select(iris,c(2:5))
head(selection3)

# using - sign to hide a particular column
selection4 <- dplyr::select(iris, -Sepal.Length, -Sepal.Width)
```

Manipulate - filter
```{r}
# Select setosa species
filtered1 <- filter(iris, Species == "setosa" )
head(filtered1,3)

# Select versicolor species with Sepal width more than 3
filtered2 <- filter(iris, Species == "versicolor", Sepal.Width > 3)
tail(filtered2)
```

Manipulate - mutate
```{r}
#To create a column “Greater.Half” which stores a logical vector (T/F)
mutated1 <- mutate(iris, Greater.Half = Sepal.Width > 0.5 * Sepal.Length)
tail(mutated1)

# not in the dplyr package
table(mutated1$Greater.Half)
```

Manipulate - arrange
```{r}
# Sepal Width by ascending order
arranged1 <- arrange(iris, Sepal.Width)
head(arranged1)

# Sepal Width by descending order
arranged2 <- arrange(iris, desc(Sepal.Width))
head(arranged2)
```

Manipulate - group by 
```{r}
# Mean sepal width by Species
gp <- group_by(iris, Species)
gp.mean <- summarise(gp,Mean.Sepal = mean(Sepal.Width))
gp.mean
```

Pipe operator 
```{r}
# To select the rows with conditions
iris %>% filter(Species == "setosa",Sepal.Width > 3.8)

# using the pipe operator to connect multiple functions 
iris %>% 
  group_by(Species) %>% 
  summarise(Mean.Length = mean(Sepal.Length))
```

**tidyr**
1. Every column is a variable
2. Every row is an observation
3. Every cell is a single values.

Pivoting 
```{r}
library (tidyr)
setwd("/Users/riversung/NTU/113-1 Fall 2024/Ocean5098 R/Rclass_Fall2024/Manipulation")
# loading data
TW_corals<-read.table('Data/tw_corals.txt', header=T, sep='\t', dec='.') 
TW_corals

# pivoiting the data, reorganizing it
# can use col(everything()) as well
TW_corals_long <- TW_corals %>%
  pivot_longer(Southern_TW:Northern_Is, names_to = "Region", values_to = "Richness")
# TW_corals_long <-TW_corals %>% pivot_longer(cols = everything(), names_to = "Region", values_to = "Richness") 
TW_corals_long 

# converting the table back to wide table
TW_corals_wide <- TW_corals_long %>%
  pivot_wider( names_from = Region, values_from = Richness) 
TW_corals_wide
```

Example
```{r}
income<-read.table('Data/metoo.txt',header=T, sep="\t", dec=".", na.strings = "n/a")
income

# using the pipe operator by separating the variable, except "state" (dont need to separate this)
income_long <- income %>%  pivot_longer(cols = -state, 
                         names_to = c("gender","work"), 
                         names_sep = "_", 
                         values_to = "income")
                         
income_long

# reverse, comvert the table back to wide table 
income_long %>% pivot_wider(names_from = c(gender,work), 
            values_from = income,
            names_sep = ".")
```

Splitting - columns 
longer way, step by step of the previous chunk 
```{r}
# Let's first create a delimited table
income_long_var <- income %>%  pivot_longer(cols = -1, 
                         names_to = "var1", 
                         values_to = "income")
income_long_var
# Split var1 column into two columns
income_sep <- income_long_var %>%  separate(col = var1, 
                    sep = "_", 
                    into = c("gender", "work"))
income_sep

#split by row
income_long_var %>% separate_rows(var1, sep = "_")
```



















